### ISSUE TITLE
Çalıntı Framework.

### ISSUE THREAD

**Issue by ozankasikci** [oguzhanaslan/Frontend-Basic-Minimal-Starter-Tool#1]
Öncelikle merhabalar, türk developerlarının gelişimine sağladığın katkı sağladığın için teşekkürler Oğuzhan. Bu can-ı gönülden yaptığından zerre şüphe duymadığım contribute'larının türk developer camiasında hakettiği yeri bulacağını umuyorum.

Gelgelelim package.json dosyasında 

"author": {
    "name": "Pedro Rogerio",
    "url": "https://github.com/pinceladasdaweb"
  },

Diyor.

Dolayısıyla bu framework'ün çalıntı olduğu izlenimi uyandırıyor. Üzücü bir durum.

Saygılar. Pedro abiye selamlar.

**Comment by oguzhanaslan** [comment]
Merhabalar ozankasikci.

Bu çalışma, göz gezdirip beğendiğim fonksiyonları, class'ları vs. vs. toparladığım bir derleme çalışması. Seninde dediğin gibi package dosyalarında kaynaklar var. Bunlar silinmemiş, tam aksine yayınlanmıştır.
Bu tür bir algı operasyonuna girişmen beni hiç şaşırtmadı. Hainliğin içine işlediği buradan belli oluyor. Sana en ağır küfürlerimi hazırladım. 

İyi Çalışmalar.

**Comment by ozankasikci** [comment]
Oysa repo'nun en başında kabak gibi "benim kendi framework'üm var" şeklinde benim gibi naif developer'ları yanıltan bir yazı var. Seni kınıyorum Oğuzhan. 

Saygılar. Pedro abiye selamlar.
